---

- include: pre-centos.yml
  when: ansible_distribution == "CentOS"

- name: Check if swap file has been created
  stat:
    path: '{{ swap_file_location }}'
  register: swap

- set_fact:
    swap_exists: '{{ swap.stat.exists }}'

- name: Create swap file in {{ swap_file_location }}
  command: 'fallocate -l "{{ swap_file_size }}" "{{ swap_file_location }}"'
  when: not swap_exists

- name: Set correct permissions on {{ swap_file_location }}
  file:
    path: '{{ swap_file_location }}'
    mode: 0600
  when: not swap_exists

- name: Create the swap
  command: 'mkswap "{{ swap_file_location }}"'
  when: not swap_exists

- name: Create mountpoint and mount the swap
  mount:
    path: 'swap'
    fstype: 'swap'
    src: '{{ swap_file_location }}'
    state: present
    opts: 'defaults'
    passno: '0'
    dump: '0'

- name: Mount the swap
  command: 'swapon -a'
  when: not swap_exists
